version: "3.8"

services:
  server:
    image: "nginx:stable-alpine"
    ports:
      - '8000:80'
    volumes: 
      -  ./app:/var/www/html
      -  ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./
      dockerfile: app.Dockerfile
    volumes:
      - ./app:/var/www/html:delegated
      - /var/www/html/vendor
  mysql:
    image: mysql:5.7
    env_file:
     - ./env/mysql.env
  
  